import Link from "next/link";
import { requirePermission, can } from "@/lib/auth";
import { stockOverview, allLots, inventoryAlerts, wasteSummary, transactions, listSuppliers, listPurchaseOrders } from "@/lib/repo/inventory";
import { listIngredients } from "@/lib/repo/meals";
import { PageHeader, Card, Tabs, Field, fmtDate, StatusBadge, Empty, Stat } from "@/components/ui";
import { formatQty } from "@/lib/grocery";
import { formatZar } from "@/lib/costing";
import { INGREDIENT_CATEGORY_LABELS } from "@/lib/types";
import { receiveLotAction, wasteAction, adjustAction, receivePurchaseOrderAction } from "@/app/actions";
import { getDb } from "@/lib/db";
import { shiftDays, todayIso } from "@/lib/finance";

const TABS = [{ key: "stock", label: "Stock levels" }, { key: "lots", label: "Lots (FIFO)" }, { key: "receive", label: "Receive stock" }, { key: "purchases", label: "Purchase orders" }, { key: "waste", label: "Waste" }, { key: "ledger", label: "Ledger" }, { key: "packaging", label: "Packaging stock" }];

export default async function Inventory({ searchParams }: { searchParams: Promise<{ tab?: string }> }) {
  const user = await requirePermission("inventory:view");
  const { tab = "stock" } = await searchParams;
  const stock = stockOverview();
  const alerts = inventoryAlerts();
  const value = stock.reduce((s, r) => s + r.value, 0);
  const edit = can(user, "inventory:edit");
  const soon = shiftDays(todayIso(), 3);
  return (
    <div>
      <PageHeader kicker="Operations" title="Inventory" actions={<Link href="/api/export/inventory" className="btn-secondary btn-sm">CSV</Link>}>Lots with batch numbers, expiry and supplier give traceability; consumption is FIFO by expiry when a batch starts cooking.</PageHeader>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-5"><Stat label="Stock value" value={formatZar(value)} sub={`${stock.length} ingredients`} /><Stat label="Low stock" value={alerts.low.length} sub="below minimum" tone={alerts.low.length ? "critical" : "good"} /><Stat label="Expiring ≤ 3 days" value={alerts.expiring.length} sub="lots" tone={alerts.expiring.length ? "warn" : "good"} /><Stat label="Waste (30 d)" value={formatZar(wasteSummary(30).total_value)} sub={`${wasteSummary(30).meals_wasted} meals wasted in production`} /></div>
      <Tabs tabs={TABS} active={tab} base="/inventory" />
      {tab === "stock" && <Card><table className="table"><thead><tr><th>Ingredient</th><th>Category</th><th>On hand</th><th>Minimum</th><th>Lots</th><th>Next expiry</th><th>Best price</th><th>Value</th></tr></thead><tbody>{stock.map((s) => { const low = s.min_stock > 0 && s.stock < s.min_stock; return <tr key={s.id} className={low ? "bg-rose-50" : ""}><td className="font-medium">{s.name}{low && <span className="badge bg-rose-100 text-rose-900 ml-2">low</span>}</td><td className="text-xs text-ink-2">{INGREDIENT_CATEGORY_LABELS[s.category]}</td><td>{formatQty(s.stock, s.base_unit)}</td><td className="text-ink-2">{formatQty(s.min_stock, s.base_unit)}</td><td>{s.lots}</td><td className={s.next_expiry && s.next_expiry <= soon ? "text-serious" : ""}>{fmtDate(s.next_expiry)}</td><td className="text-xs">{s.best_price != null ? `${formatZar(s.best_price * (s.base_unit === "each" ? 1 : 1000))} · ${s.best_supplier}` : "—"}</td><td>{formatZar(s.value)}</td></tr>; })}</tbody></table></Card>}
      {tab === "lots" && <Card title="Open lots" kicker="Ordered by expiry — consume top to bottom"><table className="table"><thead><tr><th>Batch</th><th>Ingredient</th><th>Remaining</th><th>Unit cost</th><th>Received</th><th>Expiry</th><th>Location</th><th>Supplier</th>{edit && <th>Adjust / waste</th>}</tr></thead><tbody>{allLots().map((l) => <tr key={l.id}><td className="font-mono text-xs">{l.batch_number}</td><td>{l.ingredient}</td><td>{formatQty(l.quantity_remaining, l.unit)}</td><td>{formatZar(l.unit_cost * (l.unit === "each" ? 1 : 1000))}/{l.unit === "each" ? "ea" : l.unit === "g" ? "kg" : "L"}</td><td className="text-xs">{fmtDate(l.received_at)}</td><td className="text-xs">{fmtDate(l.expiry_date)}</td><td className="text-xs">{l.storage_location}</td><td className="text-xs">{l.supplier ?? "—"}</td>{edit && <td><div className="flex gap-1"><form action={wasteAction} className="flex gap-1"><input type="hidden" name="lot_id" value={l.id} /><input name="quantity" type="number" placeholder="qty" className="input !w-20 !py-0.5 !text-xs" /><input name="reason" placeholder="reason" className="input !w-24 !py-0.5 !text-xs" /><button className="btn-secondary btn-sm">Waste</button></form><form action={adjustAction} className="flex gap-1"><input type="hidden" name="lot_id" value={l.id} /><input name="quantity" type="number" placeholder="new qty" className="input !w-20 !py-0.5 !text-xs" /><input type="hidden" name="reason" value="Stock count" /><button className="btn-secondary btn-sm">Count</button></form></div></td>}</tr>)}</tbody></table></Card>}
      {tab === "receive" && (edit ? <Card title="Receive a delivery" kicker="Creates a lot, a ledger entry and a food expense"><form action={receiveLotAction} className="grid sm:grid-cols-3 lg:grid-cols-4 gap-3"><Field label="Ingredient"><select name="ingredient_id" className="input" required>{listIngredients().map((i) => <option key={i.id} value={i.id}>{i.name} ({i.base_unit})</option>)}</select></Field><Field label="Supplier"><select name="supplier_id" className="input"><option value="">—</option>{listSuppliers().map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Batch number"><input name="batch_number" className="input" /></Field><Field label="Quantity (base units)"><input name="quantity" type="number" step="1" className="input" required /></Field><Field label="Unit cost (R per base unit)"><input name="unit_cost" type="number" step="0.0001" className="input" required /></Field><Field label="Expiry date"><input name="expiry_date" type="date" className="input" /></Field><Field label="Storage location"><select name="storage_location" className="input">{["Walk-in fridge", "Freezer", "Dry store", "Prep fridge"].map((x) => <option key={x}>{x}</option>)}</select></Field><div className="flex items-end"><button className="btn-primary">Receive</button></div></form></Card> : <Empty>No permission.</Empty>)}
      {tab === "purchases" && <Card title="Purchase orders"><table className="table"><thead><tr><th>PO</th><th>Supplier</th><th>Lines</th><th>Total</th><th>Expected</th><th>Status</th><th></th></tr></thead><tbody>{listPurchaseOrders().map((po) => <tr key={po.id}><td>#{po.id}</td><td>{po.supplier}</td><td>{po.lines}</td><td>{formatZar(po.total_zar)}</td><td>{fmtDate(po.expected_at)}</td><td><StatusBadge status={po.status} /></td><td>{edit && po.status === "sent" && <form action={receivePurchaseOrderAction}><input type="hidden" name="po_id" value={po.id} /><button className="btn-primary btn-sm">Mark received → lots</button></form>}</td></tr>)}{listPurchaseOrders().length === 0 && <tr><td colSpan={7}><Empty>No purchase orders. Create them from the grocery list.</Empty></td></tr>}</tbody></table></Card>}
      {tab === "waste" && <WasteTab />}
      {tab === "ledger" && <Card title="Inventory ledger" kicker="Every movement"><table className="table"><thead><tr><th>When</th><th>Type</th><th>Ingredient</th><th>Qty</th><th>Reason / ref</th><th>User</th></tr></thead><tbody>{transactions(150).map((t) => <tr key={t.id}><td className="text-xs">{fmtDate(t.created_at)}</td><td><StatusBadge status={t.type} /></td><td>{t.ingredient}</td><td className={t.quantity < 0 ? "text-critical" : "text-good"}>{t.quantity > 0 ? "+" : ""}{formatQty(t.quantity, t.unit)}</td><td className="text-xs text-ink-2">{t.reason} {t.reference_type ? `· ${t.reference_type} #${t.reference_id ?? ""}` : ""}</td><td className="text-xs">{t.user ?? "system"}</td></tr>)}</tbody></table></Card>}
      {tab === "packaging" && <Card title="Packaging materials"><table className="table"><thead><tr><th>Item</th><th>Unit cost</th><th>Stock</th><th>Minimum</th><th>Status</th></tr></thead><tbody>{(getDb().prepare("SELECT * FROM packaging_items ORDER BY name").all() as { id: number; name: string; unit_cost: number; stock: number; min_stock: number }[]).map((p) => <tr key={p.id}><td>{p.name}</td><td>{formatZar(p.unit_cost)}</td><td>{p.stock}</td><td>{p.min_stock}</td><td>{p.stock < p.min_stock ? <span className="badge bg-rose-100 text-rose-900">reorder</span> : <span className="badge bg-emerald-100 text-emerald-900">ok</span>}</td></tr>)}</tbody></table></Card>}
    </div>
  );
}

function WasteTab() {
  const w = wasteSummary(30);
  return <div className="grid lg:grid-cols-2 gap-4"><Card title="Ingredient waste (30 days)" kicker={`${formatZar(w.total_value)} total`}>{w.ingredients.length === 0 ? <Empty>No waste recorded.</Empty> : <table className="table"><thead><tr><th>Ingredient</th><th>Quantity</th><th>Value</th><th>Events</th></tr></thead><tbody>{w.ingredients.map((r) => <tr key={r.name}><td>{r.name}</td><td>{formatQty(r.qty, r.base_unit)}</td><td>{formatZar(r.value)}</td><td>{r.events}</td></tr>)}</tbody></table>}</Card><Card title="Production waste" kicker="Meals"><div className="stat-value">{w.meals_wasted}</div><div className="text-sm text-ink-2">meals wasted vs {w.meals_done} produced ({w.meals_done ? ((w.meals_wasted / (w.meals_done + w.meals_wasted)) * 100).toFixed(1) : 0}%)</div><p className="text-xs text-ink-2 mt-3">Record ingredient waste on the Lots tab (spoilage, trim loss) and meal waste on the production board. Both feed the analytics waste percentage.</p></Card></div>;
}
